#!/bin/bash

echo -e "\nhiding real repo\n"
if [ ! -d .git-real-repo ]
then
    mv .git .git-real-repo
fi

echo -e "\ngetting working dir repo\n"
if [ ! -d .git ]
then
    mv .git-working-dir .git
fi

echo -e "\nupdating\n"
if grep -q andy-preston/working-directory .git/config
then
    git pull
    git gui
    git push
fi

echo -e "\nhiding working dir repo\n"
if [ ! -d .git-working-dir ]
then
    mv .git .git-working-dir
fi

echo -e "\ngetting real repo\n"
if [ ! -d .git ]
then
    mv .git-real-repo .git
fi

echo -e "\nDONE\n"
